### ISSUE TITLE
Invalid parent values in toy example

### ISSUE THREAD

**Issue by manuvazquez** [tmiasko/pyjags#11]
When I try the model below, which simply consists in a categorical variable

```
import pyjags

jags_model = '''
    model {

        pmf[ 1 ] <- .25
        pmf[ 2 ] <- .25
        pmf[ 3 ] <- .25
        pmf[ 4 ] <- .25

        test ~ dcat( pmf[] )
    }
'''

jags_data = dict()
jags_model = pyjags.Model(jags_model, data=jags_data, init=dict(test=1), chains=2)
jags_samples = jags_model.sample(100, vars=['test'])
```
I get
```
JagsError: Error in node test
Invalid parent values
```

The same example works without a hitch in R (rjags).

Cheers.

**Comment by tmiasko** [comment]
I couldn't reproduce this problem with JAGS 4.2.0 and PyJAGS 1.2.1. Which version of JAGS and PyJAGS do you use?

**Comment by manuvazquez** [comment]
I'm using those exact same versions, but I was able to pin down the problem: I was running the script from an ipython session (`%run <script>`) with the pylab stuff enabled, that meaning, with the line

`c.InteractiveShellApp.pylab = 'auto'`

uncommented in the ipython profile. If I replace the above line with

`c.InteractiveShellApp.pylab = None`

then I don't get the error...really weird. It seems there is some numpy/matplotlib stuff interfering with pyjags/jags. However, running the script with `python3 <script>` directly is fine even if you do

```
from numpy import *
from matplotlib import *
```
at the beginning of the script.

If you come up with a *solution* please let me know.

Cheers.

**Comment by manuvazquez** [comment]
I found that this issue also arises when using the _locale_ package

```
import locale                                                                                       
import pyjags                                                                                       
                                                                                                    
locale.setlocale(locale.LC_ALL, 'es_ES.utf8')                                                       

jags_model = '''
    model {

        pmf[ 1 ] <- .25
        pmf[ 2 ] <- .25
        pmf[ 3 ] <- .25
        pmf[ 4 ] <- .25

        test ~ dcat( pmf[] )
    }
'''

jags_data = dict()
jags_model = pyjags.Model(jags_model, data=jags_data, init=dict(test=1), chains=2)
jags_samples = jags_model.sample(100, vars=['test'])
```
also results in

```
JagsError: Error in node test
Invalid parent values
```

**Comment by cs224** [comment]
I have the same problem, e.g. I use ipython and run into the same problem. I could work around it by putting the 'import matplotlib.pyplot as plt' statement after the pyjags.Model() statement. After that, even when importing the pyplot part, all works fine.

Does anybody know how this happens?

In any case: big thanks for the hint for how to circumvent the problem!

**Comment by tmiasko** [comment]
I must say that I tried to replicate this issue locally a few times already, but so far without any success. @cs224 could you comment on following (and anything else that you think could be relevant):

1. What is software version of jags, pyjags, python, ipython, matplotlib?
2. Does this occur in terminal version of ipython, or maybe require qt console or notebook?

**Comment by cs224** [comment]
I use the anaconda installation: Python 3.6.0 |Anaconda custom (64-bit)| (default, Dec 23 2016, 12:22:00)
Jags is v.4.1.0 as coming from the ubuntu 16.04 package list.
Pyjags is 1.2.1
ipython is 5.1.0
matplotlib is 2.0.0

Basically I just installed a computer from scratch with ubuntu 16.04 and I took everything that I can get via anaconda. Only jags itself I installed via the ubuntu package.

I hope this helps and thanks a lot for looking into this!

**Comment by tmiasko** [comment]
This seems like a parsing issue in jags. It uses atof function to convert strings to floating point numbers, which is incorrect because atof respects LC_NUMERIC. Thus, if in a given locale decimal point separator is not a period parsing will silently fail.

Possible workaround would be use a locale that uses period as a decimal point, before running pyjags:
```
import locale
locale.setlocale(locale.LC_ALL, 'C')
```

**Comment by cs224** [comment]
Yes, this makes sense. I use a German locale where the decimal point is a ',' instead of a '.' and it fails at the place where JAGS tries to parse a number. Good to know!

**Comment by manuvazquez** [comment]
Maybe we should let the developers of JAGS know... Have any of you opened a ticket or something? I can do it (I would be copy-pasting @tmiasko's comment, though,  since I don't know a thing about the JAGS source code).

Cheers.

**Comment by tmiasko** [comment]
Thanks, I already reported this upstream.

In the meantime I was planning to add a check in pyjags to ensure that locale is suitable for use with JAGS, and suggest changing it otherwise (I would rather avoid changing it automatically).

**Comment by cs224** [comment]
By the way, I just noticed that pystan has the same problem with a locale that uses a different character than the '.' for separating decimal places in numbers and the same workaround with setting the locale helps, too.

**Comment by tmiasko** [comment]
I added check that ensures that locale is compatible with JAGS in pyjags 1.2.2. 

Thanks for reporting the issue, and helping me find the root cause @manuvazquez, @cs224.
