### ISSUE TITLE
Add *.so to .gitignore?

### ISSUE THREAD

**Issue by stevenylai** [tmiasko/pyjags#12]
As titled, at this moment, if you run 'python setup.py build_ext --inplace', the *.so file will be registered as untracked files. Would be nice to ignore them. Many other Python projects with C/C++ extensions have this in their .gitignore too. Just an example: https://github.com/stan-dev/pystan/blob/develop/.gitignore

**Comment by tmiasko** [comment]
Would you like to create a pull request?

**Comment by stevenylai** [comment]
With pleasure. I thought this would be too trivial for a PR.

**Comment by tmiasko** [comment]
Thanks for PR!
