### ISSUE TITLE
No burn-in parameter

### ISSUE THREAD

**Issue by jeongyoonlee** [tmiasko/pyjags#15]
First of all, thanks for the great package! This is a great addition to `rjags` and `PyStan`/`PyMC3`.

Yet, I found that one common parameter for JAGS, `burn-in`, is missing. Hope that it can be added soon.

**Comment by tmiasko** [comment]
You can perform burn-in using sample method without actually monitoring any variables. For example:

```python
m = pyjags.Model(...)
m.sample(1000, vars=[]))
samples = m.sample(5000)
```

**Comment by jeongyoonlee** [comment]
Thanks @tmiasko. That makes sense.
