### ISSUE TITLE
dealing with missing values

### ISSUE THREAD

**Issue by michebio** [tmiasko/pyjags#16]
Hello!

Thank you very much for making available the pyjags library! 
I am trying to use it, but I have some trouble dealing with missing values. From the manual (https://pyjags.readthedocs.io/en/latest/reference.html) I understand I should use the np.ma.masked_array option, setting Mask as true when a data point is missing. However, I get a weird error “unable to resolve the following parameters” for each missing value ”Either supply values for these nodes with the data or define them on the left hand side of a relation.” I am a bit confused as usually it is not necessary to specify the missingness mechanism in JAGS if missing data are MAR.

This is a minimal working example:

`import numpy as np
import pandas as pd
import pyjags
from pyjags.model import *
import sys

x1 =np.array([0, 0, -1.5, -6.7, 1.3, -10.5, 3.3, 6.9, -0.9, -14.9, -4.8, 7.8, -9.8, 6.8, 3.2, -2.5, -5.4, -9.1, 2, 1])
x2 =np.array([0, 0, 1.3, -9.1, -5.2, 5.6, 2, -14.1, -22.5, 30.5, 21, -10.2, -9.5, -6.7, 5.6, 12.6, 15.8, 8.4, 4, 19.8])
x1 = np.ma.masked_array(data= x1, mask=[True, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False])
x2 = np.ma.masked_array(data= x2, mask=[True, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False])
y = np.array([-5.4, 21.9, -8.1, 6.4, -15.1, 11.1, 15.6, 23, 12.1, 17, -6.2, 12.6, -7, 11.9, -11.3, 13.5, -11.9, 10.9, -21.3, 1.7])

code = '''
model {
    for (i in 1:N) {
        y[i] ~ dnorm(alpha + beta1 * x1[i] + beta2 * x2[i], tau)
    }
    alpha ~ dnorm(0.0, 1.0E-4)
    beta1 ~ dnorm(0.0, 1.0E-4)
    beta2 ~ dnorm(0.0, 1.0E-4)
    sigma <- 1.0/sqrt(tau)
    tau ~ dgamma(1.0E-3, 1.0E-3)
}
'''
pyjags.load_module('glm')
model = pyjags.Model(code, data=dict(x1=x1, x2=x2, y=y, N=20), chains=4, adapt=1000)
`

This error suggests me that I should specify the missingness mechanism in jags, but it is not clear to me how to do that. In R, I would make a dataset of 0, 1 (where 1= missing value) and then give it a Bernoulli distribution. For example, this works in rjags:

`library(rjags)
library(coda)
x1<- c(0, 0, -1.5, -6.7, 1.3, -10.5, 3.3, 6.9, -0.9, -14.9, -4.8, 7.8, -9.8, 6.8, 3.2, -2.5, -5.4, -9.1, 2, 1)
x2 <- c(0, 0, 1.3, -9.1, -5.2, 5.6, 2, -14.1, -22.5, 30.5, 21, -10.2, -9.5, -6.7, 5.6, 12.6, 15.8, 8.4, 4, 19.8)
R <- matrix(c(1,1,rep(0,18),1,1,rep(0,18)),20,2)
y <- c(-5.4, 21.9, -8.1, 6.4, -15.1, 11.1, 15.6, 23, 12.1, 17, -6.2, 12.6, -7, 11.9, -11.3, 13.5, -11.9, 10.9, -21.3, 1.7)
data <- list(x1=x1,x2=x2, R=R, y=y, N=20)

cat("
model {
    for (i in 1:N) {
    		for(j in 1:2){  
        		R[i,j]~dbern(pi[i,j])
        		logit(pi[i,j])<- b1 + b2 * x1[i] + b3 * x2[i]
     		}
        y[i] ~ dnorm(alpha + beta1 * x1[i] + beta2 * x2[i], tau)
    }
    alpha ~ dnorm(0.0, 1.0E-4)
    beta1 ~ dnorm(0.0, 1.0E-4)
    beta2 ~ dnorm(0.0, 1.0E-4)
    b1 ~ dnorm(0.0, 1.0E-4)
    b2 ~ dnorm(0.0, 1.0E-4)
    b3 ~ dnorm(0.0, 1.0E-4)
    sigma <- 1.0/sqrt(tau)
    tau ~ dgamma(1.0E-3, 1.0E-3)
}
", fill=TRUE, file="model.jag")
model_JAGS <- jags.model("model.jag", data=data, inits=NULL, n.chains = 4, n.adapt=0)
m <- coda.samples(model_JAGS,c("alpha","beta1","beta2","b1","b2","b3","sigma"),n.iter=1000,thin=1)   
`
I do not understand how to translate this code into pyjags. I tried to search through the python documentation, but I feel a bit lost. I guess I am doing something silly as I am relatively new to Python. Could you provide any advice, please? 

Any help would be very much appreciated.

Michela

PS Python version 2.7.12
JAGS version 4.1.0

**Comment by tmiasko** [comment]
If you have an existing JAGS model that works with rjags, it should work with pyjags as well. No changes are required. For example, the direct translation to python could look as follows:

```python
import numpy as np
import pandas as pd
import pyjags

x1 = np.array([0, 0, -1.5, -6.7, 1.3, -10.5, 3.3, 6.9, -0.9, -14.9, -4.8, 7.8, -9.8, 6.8, 3.2, -2.5, -5.4, -9.1, 2, 1])
x2 = np.array([0, 0, 1.3, -9.1, -5.2, 5.6, 2, -14.1, -22.5, 30.5, 21, -10.2, -9.5, -6.7, 5.6, 12.6, 15.8, 8.4, 4, 19.8])
R = np.zeros((20, 2))
R[0:2, 0:2] = 1
y =  np.array([-5.4, 21.9, -8.1, 6.4, -15.1, 11.1, 15.6, 23, 12.1, 17, -6.2, 12.6, -7, 11.9, -11.3, 13.5, -11.9, 10.9, -21.3, 1.7])

code = ... # exactly the same model text as one used in rjags

pyjags.load_module('glm')
model = pyjags.Model(code, data=dict(x1=x1, x2=x2, y=y, N=20), chains=4, adapt=0)
samples = model.sample(1000, ["alpha", "beta1", "beta2", "b1", "b2", "b3", "sigma"], thin=1)
```
