### ISSUE TITLE
Minimal number of iterations

### ISSUE THREAD

**Issue by DiogoFerrari** [tmiasko/pyjags#18]
Great module! It seems the minimum number of iterations is 2000 when the parameter vars is not empty. Is there any way to have few of them if needed?

**Comment by tmiasko** [comment]
The number of iterations is provided as first argument to sample method. There is also a keyword argument named adapt in Model constructor, specifying the number of adaptation steps. It has a default value of 1000, so it might be easy to miss. Both specify the number of steps for a single chain, so total number of steps will be multiplied by the number of chains. 

You should be free to configure them as you wish. Do you have any issues with it? If so, then an example that reproduces the problem would be nice to have.

**Comment by DiogoFerrari** [comment]
Yes, I see now what was the problem. It is running as it should. Thanks
