### ISSUE TITLE
'No such file or directory' when using path for jags code.

### ISSUE THREAD

**Issue by reaver585** [tmiasko/pyjags#19]
Running python 3.6 from virtual environment. Piece of code like this:

```
path = "~/hgcm.jags"
data = # some dict
model = pyjags.Model(file=path, data=data)
```

The following happens:
```
...
self.console.checkModel(path)
console.JagsError: (2, 'No such file or directory', '~/hgcm.jags')
```

But the file is actually there. Tried to look up in console.cc, but I don't know what is exactly going on there. Any suggestions?

**Comment by tmiasko** [comment]
There is no automatic expansion of component representing user home, i.e., `~`. To make it work you have to either provide a full path manually, or expand it with `os.path.expanduser(...)`. For example:

```python
import os.path
path = os.path.expanduser("~/hgcm.jags")
...
```

**Comment by reaver585** [comment]
Thanks a lot, it worked.
