### ISSUE TITLE
also unable to install on MacOS

### ISSUE THREAD

**Issue by drbenvincent** [tmiasko/pyjags#20]
pip install pyjags

results in 

```
Collecting pyjags
  Using cached pyjags-1.2.2.tar.gz
    Complete output from command python setup.py egg_info:
    Error while executing pkg-config: [Errno 2] No such file or directory: 'pkg-config': 'pkg-config'
----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/t8/hqbgjc15023410dfyscf86g00000gn/T/pip-build-mj60gb84/pyjags/
```

**Comment by tmiasko** [comment]
You need to install pkg-config before installing pyjags.

**Comment by drbenvincent** [comment]
Thanks for the quick response.  That works now, after doing

    brew install pkg-config

and I'm up and running with the example.

It might be worth just adding something like that to the install instructions on the main repo README?

Thanks again.
