### ISSUE TITLE
Error while executing pkg-config: [Errno 2] No such file or directory: 'pkg-config'

### ISSUE THREAD

**Issue by noahmotion** [tmiasko/pyjags#4]
I just found out about pyjags, and I would like to install it. However, using pip to install from PyPI or Github, I get the following error:

    Complete output from command python setup.py egg_info:
    Error while executing pkg-config: [Errno 2] No such file or directory: 'pkg-config'

I'm using Python 3.5.1, installed with the Anaconda 2.5.0 distribution, and I have JAGS 4.1.0, on El Capitan (OS X 10.11.3).

Thanks for developing a Python interface for JAGS, by the way. I'm excited to use it.

**Comment by noahmotion** [comment]
I had missed the closed issue about installing pkg-config. I'll try to get that installed now...

**Comment by tmiasko** [comment]
I presume that installing pkg-config solved this problem. Please reopen if this is not the case.

**Comment by goyal79** [comment]
Error while executing pkg-config: [Errno 2] No such file or directory 
I am getting this message while installing pyjags
even with 'ls' command it shows the setup.py file
i am using this command 'python setup.py install'

**Comment by tmiasko** [comment]
@goyal79 you need to install pkg-config. If you are using brew, you can do it with `brew install pkg-config`. If you already have it installed, ensure directory with pkg-config binary is placed on PATH environment variable.

**Comment by goyal79** [comment]
I have tried many times...but the following error is coming..I have updated gcc, python and even again installed command line tools from Apple.

fatal error: 'unordered_set' file not found                                              
#include <unordered_set>                                                                                                           
         ^                                                                                                                         
1 error generated.                                                                                                                 
error: command 'gcc' failed with exit status 1
